import Footer from "@/components/layout/Footer"
import Header from "@/components/layout/Header/Header"
import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { Onest } from "next/font/google"
import "./globals.css"
import Providers from "./provider"

const onest = Onest({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "Enoteria Platon",
    template: "%s | Enoteria Platon",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary",
    site: "enoteriaplaton.wine",
    creator: "@enoteriaplaton",
  },
  openGraph: {
    type: "website",
    locale: "ro_RO",
    images: [
      {
        url: "https://enoteriaplaton.wine/logos/logoBlack.svg",
        width: 800,
        height: 600,
        alt: "Enoteria Platon",
      },
      {
        url: "https://enoteriaplaton.wine/logos/logoWhite.svg",
        width: 800,
        height: 600,
        alt: "Enoteria Platon",
      },
    ]
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${onest.className} overflow-x-hidden`}>
        <Providers>
          <div className="toaster">
            <Toaster richColors position="top-center" theme="light" />
          </div>
          <div className="flex min-h-screen flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
