import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next"
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { Onest } from "next/font/google"
import "./globals.css"
import Providers from "./provider"

const onest = Onest({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Enoteria Platon",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }

}>) {
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={`${onest.className} overflow-x-hidden`}>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            <div className="toaster">
              <Toaster richColors position="top-center" theme="light" />
            </div>
            <div className="flex min-h-screen flex-col">
              {children}
            </div>
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  )
}
